### ISSUE TITLE
[Bug]: Github Build distribution fails

### ISSUE THREAD

**Issue by hendrikdutoit** [hendrikdutoit/beetools#2]
**What happened**:
Pushed a branch to GitHub.  The `release` workflow failed.

**What you expected to happen**:
A  release to be distributed to PyPi.  It failed due to the `.github/workflow/release.yml` still containing code from when `setup.py ` was used to build the distribution.

**Minimal Complete Verifiable Example**:
```yaml
Change .github/workflow/release.yml from

- name: Build distributions
        shell: bash -l {0}
        run: python setup.py sdist bdist_wheel

to 

- name: Build distributions
        shell: bash -l {0}
        run: python -m build
```

**Anything else we need to know?**:

**Environment**:

- BEETools version:
- Python version:
- Operating System:
- Install method (pip, source):
